In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.model_selection import KFold

In [11]:
X = ['a', 'b', 'c', 'd', 'e', 'f']
kf = KFold(n_splits=3)

In [12]:
for train, test in kf.split(X):
    print("Train: %s, Test: %s" % (train, test))

Train: [2 3 4 5], Test: [0 1]
Train: [0 1 4 5], Test: [2 3]
Train: [0 1 2 3], Test: [4 5]


In [13]:
from sklearn.model_selection import LeaveOneOut
loo = LeaveOneOut()

In [14]:
for train, test in loo.split(X):
    print("Train: %s, Test: %s" % (train, test))

Train: [1 2 3 4 5], Test: [0]
Train: [0 2 3 4 5], Test: [1]
Train: [0 1 3 4 5], Test: [2]
Train: [0 1 2 4 5], Test: [3]
Train: [0 1 2 3 5], Test: [4]
Train: [0 1 2 3 4], Test: [5]


In [15]:
from sklearn.model_selection import train_test_split
from sklearn import datasets
from sklearn import svm

iris = datasets.load_iris()

In [16]:
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.3, random_state=2019)

In [17]:
X_train.shape, y_train.shape

((105, 4), (105,))

In [19]:
X_test.shape, y_test.shape

((45, 4), (45,))

In [20]:
model = svm.SVC(kernel='linear', C=1).fit(X_train, y_train)

In [21]:
model.score(X_test, y_test)

1.0

In [22]:
# Using Cross Validation
from sklearn.model_selection import cross_val_score
model = svm.SVC(kernel='linear', C=1)
scores = cross_val_score(model, iris.data, iris.target, cv=5)
scores

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [28]:
#multiple metrics can be specified as a list...

from sklearn.model_selection import cross_validate
from sklearn.metrics import recall_score
scoring = ['precision_macro', 'recall_macro']
model = svm.SVC(kernel='linear', C=1, random_state=1)
scores = cross_validate(model, iris.data, iris.target, scoring=scoring, cv=5, return_train_score=False)
sorted(scores.keys())

['fit_time', 'score_time', 'test_precision_macro', 'test_recall_macro']

In [26]:
scores['test_recall_macro']

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [29]:
scores

{'fit_time': array([0.00157595, 0.00089288, 0.00073504, 0.000705  , 0.00066876]),
 'score_time': array([0.00201917, 0.00129414, 0.00124907, 0.00130296, 0.00172806]),
 'test_precision_macro': array([0.96969697, 1.        , 0.96969697, 0.96969697, 1.        ]),
 'test_recall_macro': array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])}

In [30]:
scores['test_precision_macro']

array([0.96969697, 1.        , 0.96969697, 0.96969697, 1.        ])

In [31]:
from sklearn.model_selection import cross_val_predict
predicted = cross_val_predict(model, iris.data, iris.target, cv=10)

In [32]:
predicted

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [33]:
# Accuracy
from sklearn.metrics import accuracy_score

In [34]:
accuracy_score(iris.target, predicted)

0.9733333333333334