# 2019/8/25 (Sun) homework

In [1]:
import numpy as np

In [50]:
np.arange(50).reshape(5, 10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [51]:
rand_array = np.random.randint(1, 10, size=(5, 10))

In [52]:
rand_array

array([[5, 5, 9, 2, 2, 7, 3, 3, 8, 8],
       [6, 2, 5, 3, 5, 8, 4, 2, 9, 4],
       [2, 3, 6, 6, 9, 7, 4, 2, 4, 3],
       [3, 6, 2, 8, 3, 5, 1, 9, 9, 4],
       [3, 5, 8, 7, 5, 5, 6, 7, 8, 6]])

In [53]:
rand_array[2:4, 3:5]

array([[6, 9],
       [8, 3]])

In [54]:
rand_array2 = rand_array.copy()

In [55]:
rand_array2[1] = 100

In [56]:
rand_array2

array([[  5,   5,   9,   2,   2,   7,   3,   3,   8,   8],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [  2,   3,   6,   6,   9,   7,   4,   2,   4,   3],
       [  3,   6,   2,   8,   3,   5,   1,   9,   9,   4],
       [  3,   5,   8,   7,   5,   5,   6,   7,   8,   6]])

In [57]:
rand_array

array([[5, 5, 9, 2, 2, 7, 3, 3, 8, 8],
       [6, 2, 5, 3, 5, 8, 4, 2, 9, 4],
       [2, 3, 6, 6, 9, 7, 4, 2, 4, 3],
       [3, 6, 2, 8, 3, 5, 1, 9, 9, 4],
       [3, 5, 8, 7, 5, 5, 6, 7, 8, 6]])

# My Study

In [2]:
import numpy as np
np.random.random(200)

array([0.0424981 , 0.79838143, 0.48451038, 0.16218864, 0.85825598,
       0.49973627, 0.86240633, 0.53381912, 0.33469175, 0.91228282,
       0.89374867, 0.25845859, 0.43606663, 0.08599088, 0.729274  ,
       0.90629394, 0.21299148, 0.91880904, 0.28126681, 0.01791723,
       0.70885403, 0.28035937, 0.58009062, 0.08944192, 0.57164662,
       0.64849126, 0.09974507, 0.69759287, 0.46890457, 0.28803348,
       0.18961351, 0.34662338, 0.89548437, 0.31975734, 0.58363397,
       0.26083819, 0.8237665 , 0.33910137, 0.569514  , 0.56922426,
       0.18313222, 0.20216287, 0.01613938, 0.72272794, 0.77012929,
       0.52474137, 0.49567388, 0.18881378, 0.71431153, 0.85351147,
       0.41076237, 0.24483479, 0.96111528, 0.87303022, 0.71164542,
       0.51796848, 0.99037099, 0.64970799, 0.30323663, 0.1874959 ,
       0.38882782, 0.04590087, 0.15213995, 0.25963023, 0.40729489,
       0.57980994, 0.04898639, 0.54917363, 0.5406065 , 0.45989142,
       0.87445908, 0.26070395, 0.81580162, 0.10333452, 0.04612

In [9]:
np.random.randint(1, 200, 200)

array([ 58, 173, 186,  97, 155, 156, 169,  16,  20, 161, 110, 105,  49,
        65,  77,  36,  51, 158,   2,  67, 168, 194, 123, 124, 104,  76,
        44, 123,  43, 145, 132,  81,  84, 146, 122,  67,  81, 195, 145,
       194,  31,  86,  79,  41, 168, 147, 150, 100,  19,  19, 141, 193,
         3,  23, 165, 123, 199, 142,  68,  11, 126,  13, 117, 116,  12,
        23,  20,  38, 151, 184,  98, 156,  53, 157, 192, 100,  28, 147,
        70,  78, 138, 108,  38,  13,  44,  26, 148,  83, 174,  18, 119,
        86,   1,  82, 148, 134, 157, 153,  30,  29,  58, 108, 192,  98,
       110, 161, 175, 168, 173, 179,  58, 175,  26,  39, 134, 180, 192,
        52,  20, 166,  91,  49,  55,  36, 149,  74,  59,  39, 194, 114,
         6,  59, 103, 194,  94,  40, 105, 197, 154,  87,  81, 131,  27,
        88,  97,  93,   7,  14, 139,  83, 107,  42, 106, 129, 158,   1,
        79,  99,  44,  94,  46, 177,  44,  14, 158, 126,  12, 129,  19,
       124, 197,  50, 152, 149, 133,  36,  76,  61,  86,  51, 18

In [10]:
np.random.randint(1, 10000, 200)

array([1230, 5317, 8528, 2484, 7632, 6391, 4289, 3111, 1866, 3631,  205,
       9489, 3226, 2419, 9095, 4819, 9756, 6524,  726, 4911, 8439, 6987,
       5305, 6076, 7031, 3778, 5115, 2559, 3397, 8349, 8432, 8421, 7744,
       2656, 2555, 2752, 1222, 3243, 7006, 2161, 7487, 6072, 6904,  469,
       4141,  743, 8545, 7579, 3192,  745, 8743, 5482, 5867, 9108, 1984,
       4934, 3523, 3836, 8551, 5979, 1544, 2141, 4111, 5774, 5058, 2301,
       6817, 4320, 8290, 1483, 1741, 2311, 7382,  448, 9780, 7880, 8027,
       2960, 4171, 4489, 4665, 7274, 8881, 5164, 1524, 8178, 6146, 7313,
       3004, 2576, 1818,  501, 5420, 4974, 1608, 5710, 8788, 1253, 4867,
        658, 2934, 4840, 6731, 1175, 8046, 6863, 6767, 3636, 6232, 6922,
       2777, 9398, 5349, 4327, 4841, 2554, 4907, 8725, 6645, 9571, 5770,
       1956, 6944, 7834, 1312, 4339, 4337, 7451, 8840, 5875, 1278, 5059,
       3593, 7375, 9271, 1273, 8183, 2916, 1676, 1601, 3375, 4401, 2195,
       2777,  599, 6083, 8255, 8051, 3597, 3274, 56