In [1]:
import numpy as np 
from sklearn.linear_model import LogisticRegression

In [2]:
X_train = np.r_[np.random.normal(3, 1, size=50),
               np.random.normal(-1, 1, size=50)].reshape(100, -1)

In [4]:
y_train = np.r_[np.ones(50), np.zeros(50)]

In [5]:
model = LogisticRegression()

In [6]:
X_train[:10]

array([[2.70977824],
       [2.75039815],
       [2.40116956],
       [1.47693796],
       [1.38831902],
       [2.44477966],
       [2.89968318],
       [3.40881633],
       [2.94961428],
       [3.77890514]])

In [7]:
y_train[:10]

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
y_train

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
model.fit(X_train, y_train)

/Users/t_ishikawa/workspace/python_work/my-python-scripts-and-notebooks/venv/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [11]:
model.predict_proba([[0], [1], [2]])

array([[0.83005404, 0.16994596],
       [0.35370198, 0.64629802],
       [0.05777857, 0.94222143]])