In [2]:
import numpy as np

In [6]:
matrix1 = np.arange(1, 10).reshape(3, 3)

In [7]:
matrix2 = np.arange(5, 14).reshape(3, 3)

In [8]:
matrix1 * matrix2

array([[  5,  12,  21],
       [ 32,  45,  60],
       [ 77,  96, 117]])

In [9]:
print(matrix1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
print(matrix2)

[[ 5  6  7]
 [ 8  9 10]
 [11 12 13]]


In [11]:
np.dot(matrix1, matrix2)

array([[ 54,  60,  66],
       [126, 141, 156],
       [198, 222, 246]])